
services:
  streamlit:
    build:
      context: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: giovanna13
      POSTGRES_DB: embarque_2024
    ports:
      - "5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./embarque_2024.sql:/docker-entrypoint-initdb.d/embarque_2024.sql

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge